<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Hareesh" failures="1" tests="2" name="Error Validations" time="10.972" errors="0" timestamp="2024-06-07T09:36:25 IST">
  <testcase classname="Frameworks.SeleniumFrameWorks.ErrorValidations" name="LoginValidation" time="0.517"/>
  <testcase classname="Frameworks.SeleniumFrameWorks.ErrorValidations" name="ProductErrorValidation" time="3.181">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Frameworks.SeleniumFrameWorks.ErrorValidations.ProductErrorValidation(ErrorValidations.java:42)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- Error Validations -->
